I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4117, in script
    return
Exception: Could not find return label (u'game/script.rpy', 1636768274, 259).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4117, in script
    return
  File "renpy/ast.py", line 1521, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/script.rpy', 1636768274, 259).

Windows-10-10.0.17763
Ren'Py 7.4.4.1439
The Thief, the Toad, the Witch & the Mushroom 1.0
Sat Nov 13 12:51:57 2021
