I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 274, in script
    python:
  File "renpy/common/00start.rpy", line 278, in <module>
    renpy.call_in_new_context("_main_menu")
ScriptError: could not find label 'contents'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 274, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 278, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/game.py", line 344, in call_in_new_context
    return renpy.execution.run_context(False)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/script.py", line 910, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'contents'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
The Thief, the Toad, the Witch & the Mushroom. 1.0
Sun Nov  5 13:07:18 2023
