I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6660, in script
    show towncrossroadsbg at artpos
  File "game/script.rpy", line 6660, in <module>
    show towncrossroadsbg at artpos
NameError: name 'artpos' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6660, in script
    show towncrossroadsbg at artpos
  File "renpy/ast.py", line 1191, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1150, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 6660, in <module>
    show towncrossroadsbg at artpos
NameError: name 'artpos' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Lacuna. 0.81
Sat Sep  3 15:57:14 2022
