I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1131, in script
    return
Exception: Could not find return label (u'game/script.rpy', 1673165276, 11).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1131, in script
    return
  File "renpy/ast.py", line 1521, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/script.rpy', 1673165276, 11).

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Lacuna. 0.81
Sun Jan  8 18:08:18 2023
