I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 310, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 434, in script
    with Pause(5, hard)
  File "game/script.rpy", line 434, in <module>
    with Pause(5, hard)
NameError: name 'hard' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 310, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 434, in script
    with Pause(5, hard)
  File "renpy/ast.py", line 1390, in execute
    trans = renpy.python.py_eval(self.expr)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 434, in <module>
    with Pause(5, hard)
NameError: name 'hard' is not defined

Windows-10-10.0.17763
Ren'Py 7.4.4.1439
The Thief, the Toad, the Witch & the Mushroom 1.0
Sat Nov 27 13:48:27 2021
